"""Small dependency-free management page served by the standalone Body host."""

BODY_GUI_HTML = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>Body Runtime</title>
<style>
:root{color-scheme:dark;font:14px system-ui,sans-serif;background:#09110e;color:#dce9df}
body{max-width:1180px;margin:0 auto;padding:28px;background:#09110e}h1{font-size:28px;margin:4px 0}p{color:#8fa99a}.eyebrow{color:#83d5ae;font:11px ui-monospace,monospace;letter-spacing:.12em}
header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;border-bottom:1px solid #294137;padding-bottom:20px;margin-bottom:20px}.actions{display:flex;gap:8px;flex-wrap:wrap}button{border:1px solid #4b8c6b;background:#10251b;color:#d9f5e5;padding:9px 12px;cursor:pointer;border-radius:4px}button:hover{background:#1b3b29}
.stats{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-bottom:16px}.stat,.panel{border:1px solid #294137;background:#101c16;padding:14px}.stat span{display:block;color:#789589;font-size:10px;text-transform:uppercase}.stat b{display:block;margin-top:8px;font:16px ui-monospace,monospace}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.panel h2{font-size:12px;color:#9dd7b5;text-transform:uppercase;letter-spacing:.08em;margin:0 0 12px}.plugin{display:flex;justify-content:space-between;border-top:1px solid #24372d;padding:10px 0}.plugin small{display:block;color:#789589;margin-top:3px}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#747f78;margin-right:7px}.dot.on{background:#76e0a6;box-shadow:0 0 0 3px #76e0a622}.map{width:100%;aspect-ratio:1;background:#07120f;border:1px solid #315544}.map text{fill:#b9d8ca;font:2.8px ui-monospace,monospace}.map .grid{stroke:#17352d;stroke-width:.08}.map .room{fill:#0a1915;stroke:#6aa88b;stroke-width:.18}.map .body{fill:#b6f1d3}.map .target{fill:#efb17d}.map .obstacle{fill:#9b819a}.map .goal{fill:none;stroke:#e5d17b;stroke-width:.18;stroke-dasharray:.4 .2}.log{white-space:pre-wrap;overflow:auto;max-height:300px;background:#071019;color:#a8d9c2;padding:12px;font:11px/1.5 ui-monospace,monospace}.muted{color:#789589}.wide{grid-column:1/-1}@media(max-width:760px){header{display:block}.stats{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}.actions{margin-top:14px}}
</style>
</head>
<body>
<header><div><div class="eyebrow">COGNITIVE ORGANISM / BODY</div><h1>Independent Body Runtime</h1><p>Sensors, plugins and embodied world model. This page is served by the Body itself.</p></div><div class="actions"><button onclick="step()">Run supervised step</button><button onclick="resetModel()">Reset simulation</button><button onclick="refresh()">Refresh</button></div></header>
<div id="message" class="muted">Connecting to Body...</div><section class="stats"><div class="stat"><span>Runtime</span><b id="runtime">—</b></div><div class="stat"><span>World model</span><b id="mode">—</b></div><div class="stat"><span>Source</span><b id="source">—</b></div><div class="stat"><span>Steps</span><b id="steps">—</b></div><div class="stat"><span>Observation</span><b id="observation">—</b></div></section>
<div class="grid"><section class="panel"><h2>Body plugins</h2><div id="plugins" class="muted">Loading...</div><h2 style="margin-top:24px">Latest Body perception</h2><div id="perception" class="log">Waiting for an observation.</div></section><section class="panel"><h2>Embodied map</h2><svg id="map" class="map" viewBox="0 0 12 12" aria-label="Body world map"></svg><div id="map-note" class="muted">No simulated scene available.</div></section><section class="panel wide"><h2>World Model status</h2><div id="status" class="log">Loading...</div></section></div>
<script>
const $=id=>document.getElementById(id);
async function get(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw Error(path+' '+r.status);return r.json()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function renderMap(wm){const p=wm?.perception||{};const sim=wm?.sim||{};const map=$('map');map.innerHTML='';for(let i=0;i<=12;i++){map.insertAdjacentHTML('beforeend',`<line class="grid" x1="${i}" y1="0" x2="${i}" y2="12"/><line class="grid" x1="0" y1="${i}" x2="12" y2="${i}"/>`)}map.insertAdjacentHTML('beforeend','<rect class="room" x="0" y="0" width="12" height="12"/>');const sy=y=>12-(Number(y)||0);const pbody=p.body?.position||sim.body||[0,0];const shelf=sim.shelf||[1,9];map.insertAdjacentHTML('beforeend',`<circle class="goal" cx="${shelf[0]}" cy="${sy(shelf[1])}" r=".4"/><text x="${Number(shelf[0])+.5}" y="${sy(shelf[1])+.1}">goal</text>`);for(const o of p.objects||[]){const q=o.position||[0,0];const cl=o.kind==='obstacle'?'obstacle':o.kind==='target'?'target':'';map.insertAdjacentHTML('beforeend',`<circle class="${cl}" cx="${q[0]}" cy="${sy(q[1])}" r="${Math.max(.22,Math.min(.55,Number(o.size||.4)/2))}"/><text x="${Number(q[0])+.4}" y="${sy(q[1])+.1}">${esc(o.label)}</text>`)}map.insertAdjacentHTML('beforeend',`<circle class="body" cx="${pbody[0]}" cy="${sy(pbody[1])}" r=".34"/><text x="${Number(pbody[0])+.5}" y="${sy(pbody[1])+.1}">body</text>`);$('map-note').textContent=p.available?`Body observation from ${p.source}, ${p.age_seconds}s old.`:'No Body observation yet.'}
async function refresh(){try{const h=await get('/health');const w=h.worldmodel||{};$('runtime').textContent=h.runtime||'—';$('mode').textContent=w.mode||'—';$('source').textContent=w.source?.source||'—';$('steps').textContent=w.steps??0;$('observation').textContent=w.perception?.available?`${w.perception.objects?.length||0} objects`:'none';$('plugins').innerHTML=(h.plugins||[]).map(p=>`<div class="plugin"><span><i class="dot ${p.enabled?'on':''}"></i><b>${esc(p.id)}</b><small>${esc(p.role||'')}</small></span><span>${p.enabled?'Enabled':'Disabled'}</span></div>`).join('')||'<span class="muted">No plugins registered.</span>';$('perception').textContent=w.perception?.available?JSON.stringify(w.perception,null,2):'Waiting for an observation. Enable the World Model or run a supervised step.';$('status').textContent=JSON.stringify(w,null,2);renderMap(w);$('message').textContent='Body connected';}catch(e){$('message').textContent='Body unavailable: '+e.message}}
async function step(){try{await fetch('/worldmodel/step',{method:'POST'});await refresh()}catch(e){$('message').textContent=e.message)}}async function resetModel(){try{await fetch('/worldmodel/reset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clear_memory:false})});await refresh()}catch(e){$('message').textContent=e.message)}}refresh();setInterval(refresh,3000);
</script></body></html>'''
